# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 13:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commuter_name', models.CharField(max_length=120)),
                ('budget_head', models.CharField(choices=[('Admin', 'Admin'), ('Career Development', 'Career Development'), ('CFE', 'CFE'), ('CMGGA', 'CMGGA'), ('Colloquium Creative Writing', 'Colloquium Creative Writing'), ('Colloquium', 'Colloquium'), ('CSBC', 'CSBC'), ('CSGS', 'CSGS'), ('CSIP', 'CSIP'), ('Finance', 'Finance'), ('Fund Raising', 'Fund Raising'), ('GCWL', 'GCWL'), ('HR', 'HR'), ('IT', 'IT'), ('Library', 'Library'), ('Marketing YIF', 'Marketing YIF'), ('Media', 'Media'), ('OAA', 'OAA'), ('OOR', 'OOR'), ('OSL', 'OSL'), ('OUP', 'OUP'), ('Operations', 'Operations'), ('Performing Arts', 'Performing Arts'), ('Pro VC Office', 'Pro VC Office'), ('Projects', 'Projects'), ('Research Budget(Madhavi Maganti)', 'Research Budget(Madhavi Maganti)'), ('Research Budget(Tusli Sriniwasan)', 'Research Budget(Tusli Sriniwasan)'), ('Rsearch Budget(Dario Darji)', 'Rsearch Budget(Dario Darji)'), ('Science', 'Science'), ('SERI', 'SERI'), ('Sports', 'Sports'), ('Summer Semester', 'Summer Semester'), ('TCPD', 'TCPD'), ('VC Office', 'VC Office'), ('YIF', 'YIF'), ('YIF Alumni', 'YIF Alumni')], default='Car', max_length=120)),
                ('booking_type', models.CharField(choices=[('One way journey', 'One way journey'), ('Return journey', 'Return journey'), ('Airport transfer', 'Airport transfer'), ('Railway Station Transfer', 'Railway Station Transfer')], default='Unapproved', max_length=120)),
                ('pickup_address', models.TextField()),
                ('pickup_time', models.CharField(choices=[('0', '1:00'), ('1', '2:00'), ('2', '3:00'), ('3', '4:00'), ('4', '5:00'), ('5', '6:00'), ('6', '7:00'), ('7', '8:00'), ('8', '9:00'), ('9', '10:00'), ('10', '11:00'), ('11', '12:00')], default='0', max_length=120)),
                ('am_pm', models.CharField(choices=[('am', 'am'), ('am', 'am')], default='Car', max_length=120)),
                ('pickup_date', models.DateField()),
                ('commuter_contact', models.IntegerField()),
                ('approving_authority', models.CharField(max_length=120)),
                ('approving_authority_email', models.EmailField(max_length=254)),
                ('approval_status', models.CharField(choices=[('approved', 'approved'), ('unapproved', 'unapproved'), ('rejected', 'rejected')], default='Unapproved', max_length=120)),
                ('remarks', models.TextField()),
                ('note_admin', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(default='Ram', max_length=120)),
                ('driver_contact', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarrif', models.IntegerField()),
                ('total_km', models.IntegerField()),
                ('night_option', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=120)),
                ('night_charges', models.IntegerField()),
                ('toll_cost', models.IntegerField()),
                ('total', models.IntegerField()),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=120)),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('x', 'x'), ('y', 'y')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_name', models.CharField(default='Maruti', max_length=120)),
                ('registration_number', models.CharField(default='HR-XYZ-78', max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='driver',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Driver'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Transport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Vehicle'),
        ),
    ]
