# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('name_email', models.EmailField(max_length=254)),
                ('head_name', models.CharField(max_length=120)),
                ('vehicle_type', models.CharField(choices=[('x', 'x'), ('y', 'y')], default='Car', max_length=120)),
                ('booking_type', models.CharField(choices=[('x', 'x'), ('y', 'y')], default='Free', max_length=120)),
                ('pickup_address', models.TextField()),
                ('pickup_time', models.CharField(choices=[('0', '1:00'), ('1', '2:00'), ('2', '3:00'), ('3', '4:00'), ('4', '5:00'), ('5', '6:00'), ('6', '7:00'), ('7', '8:00'), ('8', '9:00'), ('9', '10:00'), ('10', '11:00'), ('11', '12:00')], default='0', max_length=120)),
                ('am_pm', models.CharField(choices=[('am', 'am'), ('am', 'am')], default='Car', max_length=120)),
                ('pickup_date', models.DateField()),
                ('contact', models.IntegerField()),
                ('approval_name', models.CharField(max_length=120)),
                ('approval_email', models.EmailField(max_length=254)),
                ('approval_status', models.CharField(choices=[('approved', 'approved'), ('unapproved', 'unapproved'), ('rejected', 'rejected')], default='Free', max_length=120)),
                ('note_user', models.TextField()),
                ('note_admin', models.TextField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
