# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pickup_time',
            field=models.CharField(choices=[('1:00', '1:00'), ('2:00', '2:00'), ('3:00', '3:00'), ('4:00', '4:00'), ('5:00', '5:00'), ('6:00', '6:00'), ('7:00', '7:00'), ('8:00', '8:00'), ('9:00', '9:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00')], default='0', max_length=120),
        ),
    ]
