# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporter',
            name='contact_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
