# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('contact_person', models.CharField(max_length=120)),
                ('contact_number', models.CharField(max_length=120)),
                ('remarks', models.TextField()),
                ('status', models.CharField(choices=[('x', 'x'), ('y', 'y')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_model_name', models.CharField(default='Maruti', max_length=120)),
                ('registration_number', models.CharField(default='HR-XYZ-78', max_length=120)),
                ('remarks', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='car',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AddField(
            model_name='booking',
            name='transport',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Transport'),
        ),
        migrations.AddField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.Vehicle'),
        ),
    ]
