# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 10:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20171004_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='email_id',
        ),
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set([('email',)]),
        ),
    ]
