# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_auto_20171006_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='am_pm',
            field=models.CharField(choices=[('am', 'am'), ('pm', 'pm')], default='Car', max_length=120),
        ),
    ]
