# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-04 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20171004_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='approval_name',
            new_name='approving_authority',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='approval_email',
            new_name='approving_authority_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='head_name',
            new_name='budget_head',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='contact',
            new_name='commuter_contact',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='commuter_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='note_user',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_contact',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='head_email',
        ),
        migrations.AlterUniqueTogether(
            name='myuser',
            unique_together=set([]),
        ),
    ]
